Feature/todo
webmarkyn/to-do-js pull request #1
Opened 2020-01-17 14:40 UTC by oscardelalanza

2020-01-17 18:10 UTC, jofer86 requested changes
## 👋 👋 Hello Team!!! I'm going to be reviewing this PR, let's take a look, shall we? 👁 👁 👁  

- Well, not much to say here, everything looks fine, functionality is there, code is modulated, although we have one single exception that is preventing me from approving this PR. Please checkout the commented code below, make sure you change what's required and resubmit for another code review- 
--------------------------------------------------------------------
Cheers,
 Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-01-17 18:10 UTC, jofer86 commented on .eslintrc.json
> +}
- This file should look like this: 
![image](https://user-images.githubusercontent.com/46115725/72635164-cc267d80-3921-11ea-9743-1adca4ada260.png)
- Please follow the steps described in the [javascript linter repo](https://github.com/microverseinc/linters-config/tree/master/javascript), to configure the linting for your project, make sure you are using the required configuration, and once that is up and running do the necessary linting (if required).

2020-01-17 22:01 UTC, oscardelalanza commented
list of changes

- linter config changed as requested

- linter checks fixed

- dom module and dom infertace refacoted to avoid dependency cycle

2020-01-18 07:41 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED

Hi Team good job on this one, good job making the changes too :+1: , please see more suggested changes  below :slightly_smiling_face: 

- There should be a defualt project that shows up once the app is run, so any todo created goes in there ![see](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png)

- currently the project is wokring properly there seem to be an error in localstorage.js with getting the length of the todos in a project , please look into that, I think in order to reproduce this you would have to delete the stored content in your localstorage :slightly_smiling_face: 

*Please make changes and request for a re-review*

**RAPHAEL NORIODE** :sunglasses:

2020-01-21 00:11 UTC, Oghenebrume50 approved these changes
### STATUS: APPROVED

Hi Team, good job on making all these changes, please merge and move on, **This is approved** :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

2020-01-21 02:51 UTC, merged